name: Set Railway Variables

on:
  workflow_dispatch:

jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Set Cloudbeds variables
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --project 201d494a-f273-4e85-ba45-30dd24d0d036 --service 58070a15-6bc2-4eee-b8e9-1bb415443ecf
          railway variables set CLOUDBEDS_API_KEY=cbat_huQOuCHeHoHl38JTpVUrZKlhJrGlse3W
          railway variables set CLOUDBEDS_CLIENT_ID=live1_8293433316474880_a6zbgrBlY2I9pihqdWkJMPSe
          railway variables set CLOUDBEDS_CLIENT_SECRET=zRdLX4J7jGKkoE9lcFBagmvspYQ6xNuV
          railway variables
